[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1"
lazy_static = "1"
reqwest = "0.12"
crossterm = "0.28"
pathfinding = "4.12"
colored = "2.2"